services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.server
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - ALPINE_MIRROR
    container_name: ${BACKEND_CONTAINER_NAME:-myweb-backend}
    ports:
      - '${BACKEND_HOST_PORT:-3302}:${BACKEND_PORT:-3302}'
    environment:
      - NODE_ENV=production
      - PORT=${BACKEND_PORT:-3302}
      - DB_PATH=/app/data/myweb.db
      # 默认 CORS_ORIGIN 指向部署的宿主机和 FRONTEND_HOST_PORT（可在环境或 .env 中覆盖）
      - CORS_ORIGIN=${CORS_ORIGIN:-http://43.163.120.212:${FRONTEND_HOST_PORT:-10010}}
    volumes:
      # 使用 Docker 命名卷管理数据，避免直接在项目目录内写入以减少权限问题
      - myweb_data:/app/data
      - myweb_uploads:/app/uploads
      - myweb_logs:/app/logs
      - myweb_preset_icons:/app/preset-icons:ro
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3302/health']
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.client
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - ALPINE_MIRROR
    container_name: ${FRONTEND_CONTAINER_NAME:-myweb-frontend}
    ports:
      # 暴露到宿主机端口（请确保服务器防火墙/安全组已允许该端口）
      - '${FRONTEND_HOST_PORT:-10010}:80'
    volumes:
      # 使用 Docker 命名卷管理上传目录
      - myweb_uploads:/usr/share/nginx/uploads:ro
    depends_on:
      - backend
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template
    restart: unless-stopped

volumes:
  # 将主机绑定挂载改为由 Docker 管理的命名卷，避免将容器可变数据写入项目代码目录
  myweb_data:
    driver: local
  myweb_uploads:
    driver: local
  myweb_logs:
    driver: local
  myweb_preset_icons:
    driver: local
