openapi: 3.0.0
info:
  title: MyWeb API
  version: 1.0.0
servers:
  # 请根据部署环境替换为实际后端地址和端口，例如: http://localhost:${BACKEND_PORT:-3000}
  - url: http://localhost:3000
paths:
  /api/wallpapers:
    $ref: './openapi/paths/wallpapers.yaml#/list'

  /api/wallpapers/active:
    $ref: './openapi/paths/wallpapers.yaml#/active'

  /api/wallpapers/random:
    $ref: './openapi/paths/wallpapers.yaml#/random'

  /api/wallpapers/{id}:
    $ref: './openapi/paths/wallpapers.yaml#/byId'

  /api/wallpapers/move:
    $ref: './openapi/paths/wallpapers.yaml#/move'

  /api/wallpapers/batch-delete:
    $ref: './openapi/paths/wallpapers.yaml#/batchDelete'

  /api/wallpapers/groups:
    $ref: './openapi/paths/wallpapers.yaml#/groups'

  /api/wallpapers/groups/{id}:
    $ref: './openapi/paths/wallpapers.yaml#/groupById'

  /api/wallpapers/groups/current:
    $ref: './openapi/paths/wallpapers.yaml#/groupsCurrent'

  /api/myapps:
    $ref: './openapi/paths/apps.yaml#/list'

  /api/myapps/{id}:
    $ref: './openapi/paths/apps.yaml#/byId'

  /api/files/upload:
    $ref: './openapi/paths/files.yaml#/upload'

  /api/music/upload:
    $ref: './openapi/paths/music.yaml#/upload'

  /api/music/tracks:
    $ref: './openapi/paths/music.yaml#/tracks'

  /api/music/tracks/{id}:
    $ref: './openapi/paths/music.yaml#/trackById'

  /api/music/tracks/{id}/stream:
    $ref: './openapi/paths/music.yaml#/trackStream'

components:
  schemas:
    Wallpaper:
      $ref: './openapi/components/schemas/wallpaper.yaml#/Wallpaper'
    ResponseWallpaper:
      $ref: './openapi/components/schemas/wallpaper.yaml#/ResponseWallpaper'
    WallpaperUpdate:
      $ref: './openapi/components/schemas/wallpaper.yaml#/WallpaperUpdate'
    GroupCreate:
      $ref: './openapi/components/schemas/wallpaper.yaml#/GroupCreate'
    GroupUpdate:
      $ref: './openapi/components/schemas/wallpaper.yaml#/GroupUpdate'
    AppCreate:
      $ref: './openapi/components/schemas/app.yaml#/AppCreate'
    AppUpdate:
      $ref: './openapi/components/schemas/app.yaml#/AppUpdate'
    MusicTrack:
      $ref: './openapi/components/schemas/music.yaml#/MusicTrack'
    MusicTrackUpdate:
      $ref: './openapi/components/schemas/music.yaml#/MusicTrackUpdate'
    ResponseMusicTrack:
      $ref: './openapi/components/schemas/music.yaml#/ResponseMusicTrack'
    ResponseMusicTrackList:
      $ref: './openapi/components/schemas/music.yaml#/ResponseMusicTrackList'
    ResponseMusicTracks:
      $ref: './openapi/components/schemas/music.yaml#/ResponseMusicTracks'
